### ISSUE TITLE
Trouble reproducing paper results

### ISSUE THREAD

**Issue by benlansdell** [mahmoodlab/FAIRY#2]
I've download the DATABASES.zip and LATENT.zip, along with the checkpoints. I then run

`python main_search.py --site organ --db_index_path DATABASES/organ/index_tree/veb.pkl --index_meta_path DATABASES/organ/index_meta/meta.pkl`

as suggested. This runs, but returns with 'Total search takes: 0'. The resulting pickle file seems empty. Further, running 

`python eval.py --site organ --result_path QUERY_RESULTS/organ/results.pkl`

as suggested, fails with:

```
Traceback (most recent call last):
  File "eval.py", line 152, in <module>
    norm_fact = 30 / sum_inv
ZeroDivisionError: division by zero
``` 

Do you have suggestions about how to get this to work?

Thanks.

**Comment by ChenChengKuan** [comment]
Hello!!
Thanks for reporting the issue. The bug is caused by the wrong instructions in the readme (it's correct now). The correct instruction is to extract DATABASE.zip under `./FAIRY` and LATENT.zip under `FAIRY/DATA` (you have to manually create a folder named DATA, I'll make it smoother in the future).  Once done, you should see something like

![Screen Shot 2022-01-04 at 3 24 23 PM](https://user-images.githubusercontent.com/13601253/148120569-25d726af-0664-475b-bc0b-3c20e739e372.png)

Should you have any question, feel free to ask. (Btw, this is a latest codebase and the results in the current Arxiv paper is a little bit dated. So you will get different results by running this codebase (mostly in mAP@5).)

**Comment by benlansdell** [comment]
Ah got it. Thanks!
