### ISSUE TITLE
When running main_search.py I get this error

### ISSUE THREAD

**Issue by markemus** [mahmoodlab/FAIRY#5]
```Traceback (most recent call last):
  File "main_search.py", line 84, in <module>
    res = db.query(patch_latent, densefeat[idx])
  File "/home/creach2/dev/SISH/database.py", line 80, in query
    C=C, T=T, thrsh=thrsh)
  File "/home/creach2/dev/SISH/database.py", line 121, in search
    if len(self.meta_clean[pre]) == 0:
AttributeError: 'HistoDatabase' object has no attribute 'meta_clean'
```

I ran artifacts_removal.py for this dataset, but maybe this is something else?

**Comment by ChenChengKuan** [comment]
Hi

This repo is used to reproduce the results of TCGA in the experiment section. The self.meta_clean is only initialized when db.leave_one_patient is called (it is called by default when you use TCGA example as long as your slide id starts with "TCGA", make sure your file structure does not break this after split function). 

As mentioned in the the comment (line 62])(https://github.com/mahmoodlab/SISH/blob/42fe005413d7ae5b4e758a99505ecb0a2e6efb0f/main_search.py#L62), you have to implement your own leave-one out and create self.meta_clean there if you are using your own data

Thanks

**Comment by markemus** [comment]
Could you advise me how to go about doing that? It seems this cleaning function drops the target filename from the searched nodes, but do I need to that if my file isn't in the database? How would I go about "cleaning" an arbitrary file?

I want to be able to search and recover similar tiles- I'm not so interested in the classification part.

**Comment by ChenChengKuan** [comment]
If you are sure that your query file is not in the database, a simple workaround is to set `is_patch=True` when calling histodatabase. By doing so, it will use the meta_data your provided as default.   (The name might be a little confusing, the reason why it is called is_patch is because this is used in `main_search_patch.py` but what it does is just like mentioned) 

Btw, if you are just want to build a system to retrieve similar patches instead of whole slide, I would recommend to use another script called `main_search_patch.py` and follow the data format there.

**Comment by markemus** [comment]
Can I search by an image without adding it to the database first? It seems like the featurization automatically adds it into the database in "Step 4 SISH database construction".

**Comment by ChenChengKuan** [comment]
Yes, you can. You just need to delete the slides you want to search from step 4.  The current codebase is mainly designed for the leave-one-out evaluation not for arbitrary downstream inference.
