### ISSUE TITLE
Interpreting results

### ISSUE THREAD

**Issue by markemus** [mahmoodlab/FAIRY#6]
I ran the whole pipeline described in the readme. I'm having trouble interpreting the results.pkl object. 

```
results_path = "~/dev/SISH/QUERY_RESULTS/breast/results.pkl"
pk = pickle.load(open(results_path, "rb"))
for x in pk['TCGA-OL-A97C-01Z-00-DX1.BDEEDEE2-6D07-4046-A8A9-D6FF8F337393']["results"][5]:
    print(x)
```

This prints out a list of dictionaries which have a "query" in common. I don't understand what this query is or why these returned objects are associated. They seem to be patches from different WSIs and the hamming distance doesn't vary much between ["results"][5] and ["results"][30].

**Comment by ChenChengKuan** [comment]
Hi
What `main_search.py` returns is the output guidedvebsearch (please refer to the panel c in Fig.1 in the paper). The full search pipeline hasn't completed until you run `eval.py` where our ranking module implemented there.  The current code is not optimized for the arbitrary downstream inference task, it is for leave-one-out evaluation in the paper (Apologize again for the inconvenience)

Here are some intuitions of the whole search pipeline: For each patch in the query, we search its nearest neighbor. After search, you see something like Fig.1c where each query patch is paired with it's neighbors. 

The key question is how do we know which query patch is most likely to be tumor ROI?  This is addressed by the subsequent ROI discovery step (referred as ranking in the paper). Intuitively, the retrieval results of a specific tumor ROI should all tagged with the same slide level label  (i.e., low entropy in terms of slide-level label because the it's ROI for a specific cancer subtype).  We use this information to determine ROI in an unsupervised way. Once the ROIs are identified, we return top search results in the identified ROI

Note that this philosophically different from normal image search where you define a similarity metric directly (d(WSI, WSI) for example). Btw, I would recommend you also check [RetCLL](https://github.com/Xiyue-Wang/RetCCL) which is also based on similar idea and have better reported performance if you want to use some SOTA.

**Comment by markemus** [comment]
Thank you, that does clear things up but RetCCL seems like the way to go then. Thanks for the help!
